# Generated by Django 5.1.3 on 2024-11-15 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('medwb_admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhaspermission',
            name='permissions',
            field=models.ManyToManyField(related_name='permission', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='adminhaspermission',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminrole', to='medwb_admins.adminrole'),
        ),
    ]
